Naming without channels
gaudio-org/BlackHole pull request #1
Opened 2022-12-09 00:57 UTC by JaegyuNoh

JJOC2ch 브랜치 하나에서 JJOC MIC / JJOC SPK 생성하도록 스크립트 수정
- 브랜치 JJOC16ch 삭제, 브랜치 JJOC2ch 이름 변경 필요 할듯

드라이버 이름 변경, deviceName = driverName("JJOC") + driverType("MIC" or "SPK")
- 일단 마이크의 경우에 1채널 / 스피커의 경우에 2채널
- GSEP이 현재 1채널이더라도 드라이버 라우팅 1채널만 하면 되니까 무관

sampleRate 48k 고정
- 최대한 스크립트 변수에 넣어봄 (코드에서 수정할 수 도 있음)

icns 아이콘 변경

(머지되면 JJOC constans.h 수정할게요.)

MIC는 출력 막기 / SPK는 입력 막기
<- 이건 좀더 봐야할 것같습니다. BlackHole 가이드대(사진)로 해보았는데 안되네요. 티켓하나 파서 좀더 디깅해보도록 하겠습니다.
<img width="876" alt="image" src="https://user-images.githubusercontent.com/64297997/206598378-ce966f16-9bce-4381-bddd-b0cda05bd2a6.png">

2022-12-09 03:14 UTC, joey-an approved these changes

2022-12-09 04:10 UTC, choiwooseok approved these changes

2022-12-09 04:14 UTC, choiwooseok requested changes
```
static UInt64 sendToApp(NSUInteger data) {
    __block UInt64 theAnswer = 0;
    NSXPCConnection *connection = [[NSXPCConnection alloc] initWithMachServiceName:@"com.gaudiolab.XPCHelper"
                                                          options:NSXPCConnectionPrivileged];
    connection.remoteObjectInterface = [NSXPCInterface interfaceWithProtocol:@protocol(XPCHelperProtocol)];
    [connection resume];
    id<XPCHelperProtocol> service = [connection remoteObjectProxyWithErrorHandler:^(NSError * _Nonnull error) {
	  NSLog(@"%@",error);
    }];
   // Input
   [service connectWithProcessIdToApp:data ioType:true withReply:^(NSError* reply){
     NSLog(@"%@", reply);
   }];
    // // Output
    // [service connectWithProcessIdToApp:data ioType:false withReply:^(NSError* reply){
    //   NSLog(@"%@", reply);
    // }];
    [connection invalidate];
    return theAnswer;
}
```
브랜치 하나로 가는 변화 할때
@JaegyuNoh  여기 보낼때 ioType 처리 바꾸는거 해줘야되요.

true / false 바꾸시는 김에.. 로그도 주석처리좀 부탁드려요

2022-12-09 06:03 UTC, choiwooseok approved these changes

2022-12-13 08:54 UTC, AlanJiwonOh requested changes

2022-12-13 08:54 UTC, AlanJiwonOh commented on Installer/create_installer.sh
> +    GCC_PREPROCESSOR_DEFINITIONS='$GCC_PREPROCESSOR_DEFINITIONS kNumber_Of_Channels='$channels'
이거랑 kBytesPerFrame의 Preprocessing으로 결정되는 시점이 trivial해서 문제 없나요?

2022-12-13 09:15 UTC, JaegyuNoh commented on Installer/create_installer.sh
> +    GCC_PREPROCESSOR_DEFINITIONS='$GCC_PREPROCESSOR_DEFINITIONS kNumber_Of_Channels='$channels'
전처리 시점에 변수 정의하면, kBytes_Per_Frame define(BlackHole.m +306)될 때 문제 없을 것 같습니다.

2022-12-13 09:18 UTC, AlanJiwonOh approved these changes

2022-12-13 10:01 UTC, merged